name: CD

on:
  push:
    branches:
      - 'current'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy_environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run deploy on staging server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME2 }}
          key: ${{ secrets.SSHKEY }}
          script:
